micronaut:
  application:
    name: grpcClient
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    greeter:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10

